### ISSUE TITLE
osrs_quest_viewer does not complete child-dependency quests when parent is completed

### ISSUE THREAD

**Issue by lucy-chapar** [Palfore/OSRSmath#16]
I noticed if you mark Desert Treasure 1 as complete the quests required for its completion stay in the graph. I think it would make more sense to the users if child quests were marked completed automatically in a circumstance like this.

**Comment by Palfore** [comment]
That's a good point. The "Complete" functionality has two purposes 1) to mark quests as complete, and 2) to hide quests. For example, a player who is restricted to 10HP may not be able to complete a quest like DT1, so for them, they would want the quest hidden - not completed. It is equivalent for the quest to not exist, so it should be hidden but it shouldn't impact the prereqs.

So, I think the best way forward would be to add a _toggle_ between whether all prerequisites should be completed, or if the user just want's to complete 1 specific quest.

An alternative could be three states per node: Uncompleted, Completed, and Hidden, but that complicates things. You can also check this short video for an example of me walking through the quests manually in a chain: https://youtube.com/shorts/V_icyISouVk?si=wVrM3ijrgbNLuwHH

**Comment by Palfore** [comment]
I added a second button "Finish", which will complete all the prerequisites. "Complete" will still only hide the selected quest. 

Here is an example of finishing While Guthix Sleeps. 

Before:
![image](https://github.com/Palfore/OSRSmath/assets/35746792/74edfa6c-46fe-4386-a99a-493cf66b71d6)

After Finishing While Guthix Sleeps (1 click):
![image](https://github.com/Palfore/OSRSmath/assets/35746792/c930cdfe-8c93-4c7d-8c47-2995d751ed92)

Thanks for the suggestion. If there are issues we can reopen.
